#!/bin/sh

DIR="$HOME/Pictures/screenshots"
FILE="$DIR/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"

# ensure directory exists
mkdir -p "$DIR"

if grim -l 0 -g "$(slurp)" "$FILE"; then
    wl-copy < "$FILE"
    notify-send " Screenshot Saved" "Saved to $FILE and copied to clipboard"
else
    notify-send " Screenshot" "Capture cancelled."
fi
