#!/bin/bash

options="󰐥  Shutdown
󰜉  Reboot
󰍃  Logout
󰤄  Suspend
󰒲  Hibernate
󰌾  Lock"

chosen=$(echo "$options" | fuzzel --dmenu \
    --width 22 \
    --lines 6 \
    --anchor top-right \
    --hide-prompt)

case "$chosen" in
    "󰐥  Shutdown")
        systemctl poweroff
        ;;
    "󰜉  Reboot")
        systemctl reboot
        ;;
    "󰍃  Logout")
        mmsg -q
        ;;
    "󰤄  Suspend")
        systemctl suspend
        ;;
    "󰒲  Hibernate")
        systemctl hibernate
        ;;
    "󰌾  Lock")
        swaylock -f -c 000000
        ;;
esac
