#!/bin/bash

options="⏻ Shutdown\n Reboot\n Logout\n⏾ Hibernate\n Lock"

chosen=$(echo -e "$options" | fuzzel --dmenu --width 20 --lines 5 --anchor top-right --hide-prompt)

case "$chosen" in
    "⏻ Shutdown")
        systemctl poweroff
        ;;
    " Reboot")
        systemctl reboot
        ;;
    " Logout")
        mmsg -q
        ;;
    "⏾ Hibernate")
        systemctl hibernate
        ;;
    " Lock")
        swaylock -f -c 000000 &
        ;;
esac
